# Welcome to Jekyll!
#

# Site settings
title: Welcome to School Messages
description:
owner:  # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: info@schoolmassages.ie
baseurl: "https://sidimar.com/schoolmessages-site/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
social:
  # behance: 
  # twitter: 
  # github: 
  # linkedin-in: 
  # facebook-official: 
  # google-plus-square: 
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
